### ISSUE TITLE
127.0.0.1:49153: connection refused

### ISSUE THREAD

**Issue by derekdon** [couchbaselabs/couchbase-server-docker#16]
docker run --net=host tleyden5iwx/couchbase-cluster-go:0.8 couchbase-fleet launch-cbs --version 3.0.1 --num-nodes 3 --userpass "user:passw0rd" --docker-tag 0.8
2015/03/23 20:53:29 Connect to etcd on localhost
2015/03/23 20:53:29 verifyEnoughMachinesAvailable()
2015/03/23 20:53:29 getJsonData error: Get http://localhost:49153/fleet/v1/machines: dial tcp 127.0.0.1:49153: connection refused
2015/03/23 20:53:29 Failed: Get http://localhost:49153/fleet/v1/machines: dial tcp 127.0.0.1:49153: connection refused

I'm trying to run this via Boot2Docker. Any ideas why this is happening?

**Comment by tleyden** [comment]
The name of this repo is actually slightly misleading, since it requires CoreOS + Docker rather than just requiring Docker.  The reason that command failed is probably a combination of two things:

* You aren't running CoreOS
* You don't have the Fleet API enabled by having this in your cloud-config: https://github.com/couchbaselabs/couchbase-server-docker/blob/master/aws-cloudformation/couchbase_server.template#L148-L153

If you give me more of an idea of what you are trying to achieve I can point you in the right direction.  Also, there's a gitter chat room here: https://gitter.im/tleyden/couchbase-cluster-go

**Comment by derekdon** [comment]
Ah thanks mate, makes sense. Continued in the gitter chat.
